[package]
name = "aurcat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
sniffer-rs = "1.1.2"
strip-ansi-escapes = "0.2.1"
toml = "0.9.7"
